from django.urls import path

from .views import (
    AnimeTVView,
    CartoonTVView,
    DoramTVView,
    HomeView,
    MoviesDetailView,
    MovieView,
    NowPlayingsView,
    PopularActorView,
    PopularMoviesView,
    SerachView,
    TopRatedView,
    TVPopularView,
    TVViews,
    UpcomingView,
    ai_recomendations,
    ai_recommendation_status,
    comment_create,
    comment_delete,
    comment_list,
    comment_vote,
)

urlpatterns = [
    path("", HomeView.as_view(), name="movies-home"),
    path("movie/<int:pk>/<str:media_type>/", MoviesDetailView.as_view(), name="movie-detail"),
    path("search/", SerachView.as_view(), name="movies-search"),
    path("popular-movies/", PopularMoviesView.as_view(), name="popular-movies"),
    path("tv-popular/", TVPopularView.as_view(), name="popular-tv"),
    path("top-rated/", TopRatedView.as_view(), name="top-rated"),
    path("now-playings/", NowPlayingsView.as_view(), name="now-playings"),
    path("upcoming/", UpcomingView.as_view(), name="upcoming"),
    path("anime-tv/", AnimeTVView.as_view(), name="anime-tv"),
    path("dorams-tv/", DoramTVView.as_view(), name="dorams-tv"),
    path("cartoon-tv/", CartoonTVView.as_view(), name="cartoon-tv"),
    path("tv/", TVViews.as_view(), name="tv"),
    path("movie/", MovieView.as_view(), name="movie"),
    path("ai/", ai_recomendations, name="ai-recomendations"),
    path("ai/status/<str:task_id>/", ai_recommendation_status, name="ai-recommendation-status"),
    path("popular-actors/", PopularActorView.as_view(), name="popular-actors"),
    path("comments/movie/<int:movie_id>/", comment_list, name="comment-list"),
    path("comments/movie/<int:movie_id>/create/", comment_create, name="comment-create"),
    path("comments/<int:pk>/delete/", comment_delete, name="comment-delete"),
    path("comments/<int:pk>/vote/", comment_vote, name="comment-vote"),
]
