# Generated by Django 5.2.5 on 2025-09-20 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovies',
            name='watched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='usermovies',
            unique_together={('user', 'movie')},
        ),
    ]
