# Generated by Django 5.2.5 on 2025-09-25 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_usermovies_watched_alter_usermovies_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='relase_date',
            new_name='release_date',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usermovies',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='rating_unique_user_movie'),
        ),
        migrations.AddConstraint(
            model_name='usermovies',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_movie'),
        ),
    ]
