# Generated by Django 5.2.5 on 2025-10-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movies_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='media_type',
            field=models.CharField(default='movie', max_length=20),
        ),
    ]
