# Generated by Django 5.2.5 on 2025-10-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movies_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='tmdb_rating',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
