# Generated by Django 5.2.5 on 2025-10-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movies_tmdb_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='tmdb_rating',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
