# Generated by Django 5.2.5 on 2025-10-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movies_tmdb_rating'),
    ]

    operations = [
        migrations.RenameModel(  # перейменував одну таблицю
            old_name='UserMovies',
            new_name='Watchlist',  
        ),
    ]
