# Generated by Django 5.2.5 on 2025-11-24 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_rename_usermovies_to_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
