# Generated by Django 5.2.5 on 2026-03-24 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_delete_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['-id']},
        ),
    ]
