# Generated by Django 5.2.5 on 2026-09-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_delete_actor_alter_movies_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
